# The following values must be passed from a secret values yaml file
#
# wmtcbm11ImageCredentials:
#   registry: quay.io
#   username: someone
#   password: sillyness
#   email: someone@host.com

# Ref: https://helm.sh/docs/howto/charts_tips_and_tricks/#creating-image-pull-secrets

{{- define "imagePullSecret" }}
{{- with .Values.wmtcbm11ImageCredentials }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: img-pull-secret-{{ include "wmtcbm11.fullname" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}