apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wmtcbm11.fullname" . }}-lic
  labels:
{{ include "wmtcbm11.labels" . | indent 4 }}
data:
  license.key: | {{- required "A valid licenseKey file is required!" .Values.licenseKey | b64enc | nindent 4 }}
