apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.customPrefix }}-tcbm-license-key
  labels:
{{ include "wmtcbm11.labels" . | indent 4 }}
type: Opaque
data:
{{ (.Files.Glob "*license.key*").AsSecrets | indent 2 }}
