apiVersion: v1
kind: Service
metadata:
  name: {{ include "wmtcbm11.fullname" . }}-hl
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    {{- include "wmtcbm11.labels" . | nindent 4 }}
spec:
  # Headless Service: This is needed for statefulset hostnames like terracotta-0 to resolve
  clusterIP: None
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  ports:
    - name: tsaport
      port: {{ .Values.portPrefix }}10
    # These ports are not normally used, uncomment if needed
    # - name: jmxport
    #  port: {{ .Values.portPrefix }}20
    # - name: groupport
    #   port: {{ .Values.portPrefix }}30
    - name: mgtport
      port: {{ .Values.portPrefix }}40
  selector:
    {{- include "wmtcbm11.selectorLabels" . | nindent 4 }}
