# Inspired from: https://github.com/SoftwareAG/webmethods-api-gateway/blob/master/samples/kubernetes/helm/cluster-deployment/apigateway/charts/terracotta/templates/terracotta-configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apigateway.customPrefix" . }}{{ .Values.tcConfig }}
  labels:
    {{- include "apigateway.labels" . | nindent 4 }}
data:
  tc-config.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <con:tc-config xmlns:con="http://www.terracotta.org/config">
        <servers>
            {{- $fullSsName      := printf "%s%s" ( include "apigateway.customPrefix" . ) .Values.statefulsetName }}
            {{- $fullServiceName := printf "%s%s" ( include "apigateway.customPrefix" . ) .Values.serviceName }}
            <server host="{{ $fullSsName }}-0.{{ $fullServiceName }}" name="{{ $fullSsName }}-0" bind="0.0.0.0" jmx-enabled="false">
                <logs>stdout:</logs>
                <tsa-port bind="0.0.0.0">{{ .Values.port }}</tsa-port>
                <tsa-group-port bind="0.0.0.0">{{ .Values.syncPort }}</tsa-group-port>
            </server>
            <client-reconnect-window>120</client-reconnect-window>
        </servers>
    </con:tc-config>
