# Inspired from: https://github.com/SoftwareAG/webmethods-api-gateway/blob/master/samples/kubernetes/helm/cluster-deployment/apigateway/charts/terracotta/templates/terracotta-configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.customPrefix }}-tc-config
  labels:
    {{- include "wmtcbm11.labels" . | nindent 4 }}
data:
  tc-config.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <con:tc-config xmlns:con="http://www.terracotta.org/config">
        <servers>
            {{- $fullSsName      := printf "%s%s" .Values.global.customPrefix .Values.statefulsetName }}
            {{- $fullServiceName := printf "%s%s" .Values.global.customPrefix .Values.serviceName }}
            <server host="{{ $fullSsName }}-0.{{ $fullServiceName }}.{{ .Release.Namespace }}.svc.cluster.local"
                    name="{{ $fullSsName }}-0.{{ $fullServiceName }}.{{ .Release.Namespace }}.svc.cluster.local"
                    bind="0.0.0.0" jmx-enabled="false">
                <logs>stdout:</logs>
                <data>{{ .Values.mountPaths.diskstore }}</data>
                <index>{{ .Values.mountPaths.index }}</index>
                <data-backup>{{ .Values.mountPaths.backups }}</data-backup>
                <tsa-port bind="0.0.0.0">{{ .Values.portPrefix }}10</tsa-port>
                <jmx-port bind="0.0.0.0">{{ .Values.portPrefix }}20</jmx-port>
                <tsa-group-port bind="0.0.0.0">{{ .Values.portPrefix }}30</tsa-group-port>
                <management-port bind="0.0.0.0">{{ .Values.portPrefix }}40</management-port>
            </server>
            <client-reconnect-window>120</client-reconnect-window>
        </servers>
    </con:tc-config>
